import { Acme } from "next/font/google";
import NavBar from "./comps/NavBar";
import Footer from "./comps/Footer";
import "./globals.css";

const inter = Acme({ subsets: ["latin"], 
                      weight: ['400']});

export const metadata = {
  title: "Blogging Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        
        
        <div className="min-h-[90vh]">

        {children}
        </div>
        
        <Footer />
        </body>
    </html>
  );
}
